name: coverity-linux-and-python-report

on: [workflow_dispatch, workflow_call]

permissions:
  contents: read

jobs:
  build:

    runs-on: ci-kw-linux
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive

    - name: coverity-python
      run: |
        ci-cov-python.sh

    - name: coverity-linux
      run: |
        mkdir build
        cd build
        cmake ..
        ci-cov-linux.sh

    - name: coverity-linux-and-python-report
      run: |
        ci-cov-linux-report.sh PCM.linux.and.python

    - name: upload-artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: coverity-linux-and-python-report-${{ github.sha }}
        path: "*-Report.pdf"
