name: fuzz-short-job

on:
  # manual triggering
  workflow_dispatch:


permissions:
  contents: read

jobs:
  fuzz:
    runs-on: ci-test
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        submodules: recursive

    - name: Build and test
      run: |
        cmake --version
        set -o pipefail
        mkdir build
        cd build
        bash ${{ github.workspace }}/tests/fuzz.sh 10 2>&1 | tee fuzz-log.txt
        cd ..

    - name: Show report
      run: |
        cat build/report.txt
        echo "Fuzzing completed"

    - name: upload-artifact
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: fuzz-log-${{ github.sha }}
        path: "build/fuzz-log.txt"


