name: FreeBSD build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
      with:
        egress-policy: audit

    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: recursive
    - name: build in FreeBSD VM
      id: build
      uses: cross-platform-actions/action@2d97d42e1972a17b045fd709a422f7e55a86230d
      with:
        memory: 2048
        shell: sh
        operating_system: freebsd
        version: '14.2'
        run: |
          sudo mkdir -p /usr/local/etc/pkg/repos
          sudo sh -c 'echo "FreeBSD: { url: \"https://pkg.FreeBSD.org/\${ABI}/quarterly\", mirror_type: \"srv\", enabled: yes }" > /usr/local/etc/pkg/repos/FreeBSD.conf'
          sudo pkg update -f
          sudo pkg upgrade -y
          sudo pkg install -y curl gmake cmake
          pwd
          ls -lah
          whoami
          env
          freebsd-version
          cmake -B build -DCMAKE_INSTALL_PREFIX=.
          cd build && gmake install
